name: modeling
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astor=0.8.1
  - asttokens=2.0.5
  - attrs=22.1.0
  - autograd=1.6.2
  - autograd-gamma=0.5.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - biopython=1.83
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2024.9.24
  - cached_property=1.5.2
  - cffi=1.15.1
  - chardet=5.1.0
  - cloudpickle=3.0.0
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=38.0.4
  - cudatoolkit=11.8.0
  - cycler=0.11.0
  - cython=3.0.10
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.2.10
  - fftw=3.3.9
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - formulaic=0.6.4
  - freetype=2.10.4
  - future=0.18.3
  - giflib=5.2.1
  - glib=2.69.1
  - graphlib-backport=1.0.3
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - hdbscan=0.8.33
  - icu=58.2
  - idna=3.4
  - importlib_resources=6.0.1
  - interface_meta=1.3.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.3.4
  - jupyter_console=6.4.4
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.5
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=14.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm14=14.0.6
  - libopenblas=0.3.20
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libstdcxx-ng=14.1.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxgboost=2.1.1
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lifelines=0.27.7
  - llvm-openmp=14.0.6
  - logomaker=0.8
  - lxml=4.9.1
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - openpyxl=3.0.10
  - openssl=1.1.1w
  - packaging=23.1
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=2.5.2
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=2.1.1
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.1.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.9
  - pytz=2022.7
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.0
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - scikit-learn=1.2.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.0
  - setuptools=68.0.0
  - shap=0.45.1
  - sip=6.6.2
  - six=1.16.0
  - slicer=0.0.8
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.1
  - traitlets=5.7.1
  - typing_extensions=4.4.0
  - tzdata=2023c
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - xgboost=2.1.1
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==5.3.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - flatbuffers==23.5.26
      - gast==0.4.0
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.57.0
      - h5py==3.9.0
      - importlib-metadata==6.8.0
      - jax==0.4.14
      - keras==2.12.0
      - libclang==16.0.6
      - llvmlite==0.42.0
      - markdown==3.4.4
      - markupsafe==2.1.3
      - ml-dtypes==0.2.0
      - numba==0.59.0
      - numpy==1.24.3
      - nvidia-cublas-cu11==2022.4.8
      - nvidia-cublas-cu117==11.10.1.25
      - nvidia-cudnn-cu11==8.6.0.163
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==4.24.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pynndescent==0.5.11
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.11.1
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.1
      - tensorflow==2.12.1
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.33.0
      - termcolor==2.3.0
      - tqdm==4.66.2
      - typing-extensions==4.5.0
      - umap-learn==0.5.5
      - urllib3==1.26.16
      - werkzeug==2.3.6
      - wrapt==1.14.1