name: preprocessing
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.5.0
  - argon2-cffi=20.1.0
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2024.9.24
  - certifi=2022.12.7
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - expat=2.6.3
  - fftw=3.3.9
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.2
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.4.4
  - jupyter_core=4.11.2
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.19.0
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.2.1
  - libgcc-ng=13.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.14
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.5.2
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.7.0
  - ncls=0.0.68
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openpyxl=3.0.10
  - openssl=1.0.2u
  - packaging=22.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.7
  - pytz=2022.7
  - pyzmq=23.2.0
  - qt=5.9.6
  - qtconsole=5.4.0
  - qtpy=2.2.0
  - readline=7.0
  - regex=2022.9.13
  - requests=2.28.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=4.19.8
  - six=1.16.0
  - sniffio=1.2.0
  - sorted_nearest=0.0.37
  - soupsieve=2.3.2.post1
  - sqlite=3.33.0
  - terminado=0.17.1
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.1.1
  - urllib3=1.26.14
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - asynctest==0.13.0
      - biopython==1.81
      - cptac==0.7.1
      - datasets==2.13.2
      - dill==0.3.6
      - filelock==3.12.2
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - huggingface-hub==0.16.4
      - multidict==6.0.5
      - multiprocess==0.70.14
      - natsort==8.4.0
      - pandas==0.25.3
      - pyarrow==12.0.1
      - pyranges==0.0.129
      - pyyaml==6.0.1
      - sorted-nearest==0.0.39
      - tabulate==0.9.0
      - tqdm==4.66.5
      - xxhash==3.5.0
      - yarl==1.9.4
